### ISSUE TITLE
[BUG] No Icon displayed on KDE Menu

### ISSUE THREAD

**Issue by Lord-Haji** [Enrico204/Whatsapp-Desktop#57] opened 2017-11-22 13:45 UTC
Although its showing up right on the notifications tray, but no icon shows up in the KDE Menu

**Comment by Enrico204** [comment] 2017-11-25 12:13
Which distro are you using? Version of KDE?

**Comment by Enrico204** [comment] 2018-01-01 17:10
Hi @Lord-Haji , I'm closing this issue because I can't reproduce this behavior. If you still have this issue on latest release, feel free to reopen this issue :-)

**Closed by Enrico204** 2018-01-01 17:10 UTC
Labels: triage/major-bug
