### ISSUE TITLE
Fonts rendering as rectangles after upgrade

### ISSUE THREAD

**Issue by boban-dj** [Enrico204/Whatsapp-Desktop#13] opened 2017-07-28 09:36 UTC
After Archlinux upgrade , when attaching files or photos, the upload dialogs fonts are messed up.

```
pacman -Qi whatsapp-desktop
Name            : whatsapp-desktop
Version         : 0.3.10-1
Description     : Unofficial whatsapp web desktop client. Build with Electron.
Architecture    : x86_64
URL             : https://github.com/Enrico204/Whatsapp-Desktop
Licenses        : MIT
Groups          : None
Provides        : whatsapp-desktop
Depends On      : libnotify  gconf
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 101.07 MiB
Packager        : Unknown Packager
Build Date      : Thu 27 Jul 2017 06:49:39 PM CEST
Install Date    : Thu 27 Jul 2017 06:50:49 PM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

```
$ uname -a
Linux archz800 4.9.37-1-lts #1 SMP Wed Jul 12 19:22:39 CEST 2017 x86_64 GNU/Linux
```

**See some screen shots**
![screenshot_2017-07-28_11-30-21](https://user-images.githubusercontent.com/5364226/28711716-decd5a96-7388-11e7-95c6-6c4606bfcff3.png)
![screenshot_2017-07-28_11-30-42](https://user-images.githubusercontent.com/5364226/28711715-deccbf8c-7388-11e7-9957-5aac4a67292b.png)

**Comment by Enrico204** [comment] 2017-07-28 11:21
Thanks, I'll setup a VM ASAP in order to reproduce this bug!

Which desktop environment are you using? Gnome?

**Comment by boban-dj** [comment] 2017-07-28 11:24
i3 with xfce4. You can let me know what kind of info you need.

**Comment by Enrico204** [comment] 2017-07-28 11:27
That's all for now, I'll install ArchLinux and try whatsapp-desktop. I'll update as soon as I have some news :-)

**Comment by boban-dj** [comment] 2017-07-28 11:28
thanks Enrico204

**Comment by boban-dj** [comment] 2017-07-28 11:57
btw if you install whatsapp-desktop from the AUR, download a snapshot, make it with: ` makepkg -s--skipinteg` , then install with` pacman -U` 
cause the sha-sum was not updated

**Comment by Enrico204** [comment] 2017-07-28 17:00
I tried with Gnome and everthing is Ok, I'm installing Xfce4 to test against your environment :-)

**Comment by Enrico204** [comment] 2017-07-28 17:14
Ok I've tested on Xfce4 environment, and I have no issues with that window. Maybe it's a locale setting. Which locale do you have?

**Comment by boban-dj** [comment] 2017-07-28 19:04
```
locale

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Comment by boban-dj** [comment] 2017-07-28 19:33
I updated the fonts cache: `#  fc-cache -f -v`
also when I change the fonts in the appearance settings of xfce4, the squares change to other type of squares. With other applications I have no problems.

**Comment by boban-dj** [comment] 2017-07-28 20:17
This is the output of xprop for the file chooser dialog:
boban@archz800 ~/.config $ xprop
```
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x3600001
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
WM_TRANSIENT_FOR(WINDOW): window id # 0x3800001
WM_WINDOW_ROLE(STRING) = "GtkFileChooserDialog"
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 56623573
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_USER_TIME(CARDINAL) = 4559390
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x36001d4
WM_CLIENT_LEADER(WINDOW): window id # 0x3600001
_NET_WM_PID(CARDINAL) = 7832
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "archz800"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 478 by 272
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Whatsapp", "Whatsapp"
WM_ICON_NAME(STRING) = 
_NET_WM_ICON_NAME(UTF8_STRING) = 
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) =
```

**Comment by boban-dj** [comment] 2017-07-28 20:18
Some more info:
```
~/.config/gtk-3.0 $ cat settings.ini
[Settings]
gtk-theme-name=Clearlooks-Phenix
gtk-icon-theme-name=Classic95
gtk-font-name=DejaVu Sans Mono 10
gtk-cursor-theme-name=Neutral
gtk-cursor-theme-size=16
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium
gtk-xft-rgba=none


~/.config/gtk-3.0 $ cat ~/.config/gtk-2.0/gtkfilechooser.ini

[Filechooser Settings]
LocationMode=filename-entry
ShowHidden=true
ShowSizeColumn=true
GeometryX=0
GeometryY=0
GeometryWidth=792
GeometryHeight=701
SortColumn=name
SortOrder=ascending
StartupMode=recent
```

**Comment by boban-dj** [comment] 2017-07-29 05:49
**SOLVED:**

Found the package that gave the problem from these threads.
[https://bbs.archlinux.org/viewtopic.php?id=226967](url)
[https://www.reddit.com/r/archlinux/comments/6dodbn/unrecognized_characters_in_gtk_file_chooser/](url)

Downgraded pango and the font problem gets resolved.
The current pango in Archlinux is `extra/pango 1.40.7-1 [installed: 1.40.5-1]`

**Comment by Enrico204** [comment] 2017-07-29 06:14
Great! I'll look at these links as soon as possible :-)

**Comment by Enrico204** [comment] 2017-07-31 09:22
Ok this issue is caused by Electron. We need to wait for an upstream update. In the meantime, I think that I'll write down a message into README.md and see if downgrade can be forced into the AUR package.
Thanks @boban-dj :-)

**Comment by boban-dj** [comment] 2017-09-25 05:53
Bug still exists, I need to downgrade" warning: downgrading package pango (1.40.12-1 => 1.40.5-1)
after every upgrade of the system.
Do you know more?

**Comment by boban-dj** [comment] 2017-09-25 06:04
Sorry Enrico204, I forgot to upgrade whatsapp-desktop. So now  with whatsapp-desktop Version : 0.3.12-1
and pango Version : 1.40.12-1 the issue is gone. Thanks

**Comment by Enrico204** [comment] 2017-09-25 06:14
Good :-)
I'll close this issue for now. Thank you :-)

**Closed by Enrico204** 2017-09-25 06:14 UTC
Labels: bug, upstream
