### ISSUE TITLE
Do not create menu link

### ISSUE THREAD

**Issue by AyelGoth** [Enrico204/Whatsapp-Desktop#22] opened 2017-08-25 04:03 UTC
The installer for 64-bit linux does not create the menu item in the KDE launcher. You have to create it manually.

**Comment by Termuellinator** [comment] 2017-08-25 09:31
which installer? For me, the AUR-Package created the correct .desktop-entry in KDE :)

**Comment by Enrico204** [comment] 2017-08-25 12:18
Hi @AyelGoth , which distro are you using?

**Comment by AyelGoth** [comment] 2017-08-26 12:19
Kubuntu 17.04

2017-08-25 9:18 GMT-03:00 Enrico <notifications@github.com>:

**Comment by Enrico204** [comment] 2017-08-26 22:59
I'm downloading Kubuntu for testing, I'll update this issue soon :-)

**Comment by Enrico204** [comment] 2017-08-27 00:10
Ok I verified that the current released version (0.3.12) is not creating the right `.desktop` file - in fact, this issue is the same/duplicate of #17 (fixed in `master` branch). I'll release a new version (0.3.13) as soon as I have fixed all bugs scheduled for that release :-)

**Closed by Enrico204** 2017-08-27 00:10 UTC
